spring:
  datasource:
    url: jdbc:h2:file:/temp/data/testdb
    username: foo
    password: foo
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect