spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: foo
    password: foo
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.dll-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true